Cleanups in mount-chroot service

diff --git a/etc/init.d/mount-chroot b/etc/init.d/mount-chroot
--- a/etc/init.d/mount-chroot
+++ b/etc/init.d/mount-chroot
@@ -3,9 +3,8 @@
 # Distributed under the terms of the GNU General Public License v2
 
 CHROOT=${SVCNAME#*.}
-if [ ${SVCNAME} = "mount-chroot" ]; then
-	CHROOT_PATH=""
-fi
+TMPDIR="/tmp/chroot-mount/${CHROOT}"
+
 
 depend() {
 	need localmount
@@ -13,45 +12,55 @@ depend() {
 }
 
 start() {
+	if [ ${SVCNAME} = "mount-chroot" ]; then
+		eerror "You must not call mount-chroot directly."
+		eerror "Create a symlink pointing to the service name (chroot-mount.name)"
+		return 1
+	fi
 	if [ "${CHROOT_PATH}" = "" ]; then
 		eerror "You must set the variable CHROOT_PATH in the config file"
 		return 1
 	fi
+	local eroot portdir distdir
+	eroot="$(portageq envvar EROOT)"
+	portdir="$(portageq get_repo_path ${eroot} gentoo)"
+	distdir="$(portageq envvar DISTDIR)"
+
 	ebegin "Mounting chroot directories"
 	mount --rbind /dev "${CHROOT_PATH}"/dev > /dev/null &
 	mount -t proc none "${CHROOT_PATH}"/proc > /dev/null &
 	mount -o bind /sys "${CHROOT_PATH}"/sys > /dev/null &
 
-	# mkdir new /tmp/mount-chroot/chrootname and bind it instead of /tmp for more isolation
-	mount -o bind /tmp "${CHROOT_PATH}"/tmp > /dev/null &
+	mkdir -p "${TMPDIR}" || die "Could not create tmp dir ${TMPDIR}"
+	mount -o bind "${TMPDIR}" "${CHROOT_PATH}"/tmp > /dev/null &
 
-	if [[ $PORTAGE -eq 1 ]]; then
+	if [[ "$PORTAGE" -eq 1 ]]; then
 		if [ ! -d "${CHROOT_PATH}/usr/portage" ]; then
 			mkdir -p "${CHROOT_PATH}/usr/portage" || die "Could not create portage dir"
 		fi
 
 		local rwmountopt="-r"
-		if [[ $PORTAGE_RW -eq 1 ]]; then
-			RW="-w"
+		if [[ "$PORTAGE_RW" -eq 1 ]]; then
+			rwmountopt="-w"
 		fi
 
 		# rbind is needed to mount potential nfs shared portage dir from host
-		mount --rbind "${rwmountopt}" /usr/portage "${CHROOT_PATH}/usr/portage" > /dev/null &
-	else
-		if [[ $PORTAGE_DIST -eq 1 ]]; then
-			if [ ! -d "${CHROOT_PATH}/usr/portage/distfiles" ]; then
-				mkdir -p "${CHROOT_PATH}/usr/portage/distfiles" || die "Could not create portage distfiles dir"
-			fi
-
-			local rwmountopt="-r"
-			if [[ $PORTAGE_DIST_RW -eq 1 ]]; then
-				RW="-w"
-			fi
-
-			# rbind is needed to mount potential nfs shared portage dir from host
-			mount --rbind "${rwmountopt}" /usr/portage/distfiles "${CHROOT_PATH}/usr/portage/distfiles" > /dev/null &
-		fi
+		mount --rbind "${rwmountopt}" "${portdir}" "${CHROOT_PATH}/usr/portage" > /dev/null &
 	fi
+	if [[ "${PORTAGE_DIST}" -eq 1 ]]; then
+		if [ ! -d "${CHROOT_PATH}/usr/portage/distfiles" ]; then
+			mkdir -p "${CHROOT_PATH}/usr/portage/distfiles" || die "Could not create portage distfiles dir"
+		fi
+
+		local rwmountopt="-r"
+		if [[ "$PORTAGE_DIST_RW" -eq 1 ]]; then
+			rwmountopt="-w"
+		fi
+
+		# rbind is needed to mount potential nfs shared portage dir from host
+		mount --rbind "${rwmountopt}" "${distdir}" "${CHROOT_PATH}/usr/portage/distfiles" > /dev/null &
+	fi
+
 	eend $? "An error occurred while mounting chroot directories"
 }
 
